version: '3'
 
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: "mydatabase"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - lan

volumes:
  mysql-data:
networks:
  lan:
